import 'package:leavify/features/Authentication/domain/response/get_all_response.dart';

/// Dummy JSON list for GetAllResponse
const List<Map<String, dynamic>> dummyGetAllResponseJson = [
  {
    "profileImage": "https://example.com/profiles/user1.png",
    "firstName": "John",
    "lastName": "Doe",
    "role": "Developer",
    "startDate": "2025-10-01T00:00:00Z",
    "endDate": "2025-10-03T00:00:00Z",
    "reason": "Personal work",
    "status": "APPROVED",
    "leaveId": "L001",
    "escalated": false,
    "documentsCount": 1,
    "designation": "Software Engineer",
  },
  {
    "profileImage": "https://example.com/profiles/user2.png",
    "firstName": "Jane",
    "lastName": "Smith",
    "role": "Designer",
    "startDate": "2025-10-05T00:00:00Z",
    "endDate": "2025-10-06T00:00:00Z",
    "reason": "Medical",
    "status": "PENDING",
    "leaveId": "L002",
    "escalated": false,
    "documentsCount": 2,
    "designation": "UI/UX Designer",
  },
  {
    "profileImage": "https://example.com/profiles/user3.png",
    "firstName": "Alice",
    "lastName": "Brown",
    "role": "QA",
    "startDate": "2025-10-07T00:00:00Z",
    "endDate": "2025-10-07T00:00:00Z",
    "reason": "Personal work",
    "status": "REJECTED",
    "leaveId": "L003",
    "escalated": true,
    "documentsCount": 0,
    "designation": "QA Engineer",
  },
  {
    "profileImage": "https://example.com/profiles/user4.png",
    "firstName": "Bob",
    "lastName": "Johnson",
    "role": "Developer",
    "startDate": "2025-10-10T00:00:00Z",
    "endDate": "2025-10-12T00:00:00Z",
    "reason": "Vacation",
    "status": "APPROVED",
    "leaveId": "L004",
    "escalated": false,
    "documentsCount": 1,
    "designation": "Frontend Developer",
  },
  {
    "profileImage": "https://example.com/profiles/user5.png",
    "firstName": "Charlie",
    "lastName": "Davis",
    "role": "Designer",
    "startDate": "2025-10-14T00:00:00Z",
    "endDate": "2025-10-16T00:00:00Z",
    "reason": "Personal",
    "status": "PENDING",
    "leaveId": "L005",
    "escalated": false,
    "documentsCount": 0,
    "designation": "Graphic Designer",
  },
  {
    "profileImage": "https://example.com/profiles/user6.png",
    "firstName": "David",
    "lastName": "Evans",
    "role": "QA",
    "startDate": "2025-10-18T00:00:00Z",
    "endDate": "2025-10-19T00:00:00Z",
    "reason": "Family function",
    "status": "APPROVED",
    "leaveId": "L006",
    "escalated": true,
    "documentsCount": 1,
    "designation": "QA Analyst",
  },
  {
    "profileImage": "https://example.com/profiles/user7.png",
    "firstName": "Emma",
    "lastName": "Wilson",
    "role": "Developer",
    "startDate": "2025-10-20T00:00:00Z",
    "endDate": "2025-10-22T00:00:00Z",
    "reason": "Travel",
    "status": "PENDING",
    "leaveId": "L007",
    "escalated": false,
    "documentsCount": 0,
    "designation": "Backend Developer",
  },
  {
    "profileImage": "https://example.com/profiles/user8.png",
    "firstName": "Fiona",
    "lastName": "Miller",
    "role": "Designer",
    "startDate": "2025-10-23T00:00:00Z",
    "endDate": "2025-10-24T00:00:00Z",
    "reason": "Medical",
    "status": "APPROVED",
    "leaveId": "L008",
    "escalated": false,
    "documentsCount": 2,
    "designation": "UX Designer",
  },
  {
    "profileImage": "https://example.com/profiles/user9.png",
    "firstName": "George",
    "lastName": "Taylor",
    "role": "QA",
    "startDate": "2025-10-25T00:00:00Z",
    "endDate": "2025-10-26T00:00:00Z",
    "reason": "Family work",
    "status": "REJECTED",
    "leaveId": "L009",
    "escalated": true,
    "documentsCount": 1,
    "designation": "QA Engineer",
  },
  {
    "profileImage": "https://example.com/profiles/user10.png",
    "firstName": "Hannah",
    "lastName": "Anderson",
    "role": "Developer",
    "startDate": "2025-10-27T00:00:00Z",
    "endDate": "2025-10-29T00:00:00Z",
    "reason": "Vacation",
    "status": "APPROVED",
    "leaveId": "L010",
    "escalated": false,
    "documentsCount": 1,
    "designation": "Full Stack Developer",
  },
  {
    "profileImage": "https://example.com/profiles/user11.png",
    "firstName": "Ian",
    "lastName": "Thomas",
    "role": "Designer",
    "startDate": "2025-10-30T00:00:00Z",
    "endDate": "2025-11-01T00:00:00Z",
    "reason": "Medical",
    "status": "PENDING",
    "leaveId": "L011",
    "escalated": false,
    "documentsCount": 0,
    "designation": "Graphic Designer",
  },
  {
    "profileImage": "https://example.com/profiles/user12.png",
    "firstName": "Julia",
    "lastName": "Moore",
    "role": "QA",
    "startDate": "2025-11-02T00:00:00Z",
    "endDate": "2025-11-03T00:00:00Z",
    "reason": "Personal",
    "status": "APPROVED",
    "leaveId": "L012",
    "escalated": false,
    "documentsCount": 1,
    "designation": "QA Analyst",
  },
  {
    "profileImage": "https://example.com/profiles/user13.png",
    "firstName": "Kevin",
    "lastName": "Lee",
    "role": "Developer",
    "startDate": "2025-11-04T00:00:00Z",
    "endDate": "2025-11-06T00:00:00Z",
    "reason": "Travel",
    "status": "PENDING",
    "leaveId": "L013",
    "escalated": true,
    "documentsCount": 0,
    "designation": "Frontend Developer",
  },
  {
    "profileImage": "https://example.com/profiles/user14.png",
    "firstName": "Laura",
    "lastName": "White",
    "role": "Designer",
    "startDate": "2025-11-07T00:00:00Z",
    "endDate": "2025-11-08T00:00:00Z",
    "reason": "Family work",
    "status": "APPROVED",
    "leaveId": "L014",
    "escalated": false,
    "documentsCount": 1,
    "designation": "UX Designer",
  },
  {
    "profileImage": "https://example.com/profiles/user15.png",
    "firstName": "Michael",
    "lastName": "King",
    "role": "QA",
    "startDate": "2025-11-09T00:00:00Z",
    "endDate": "2025-11-10T00:00:00Z",
    "reason": "Medical",
    "status": "REJECTED",
    "leaveId": "L015",
    "escalated": true,
    "documentsCount": 2,
    "designation": "QA Engineer",
  },
];

/// Convert JSON list to List<GetAllResponse>
final List<GetAllResponse> dummyGetAllData = dummyGetAllResponseJson
    .map((json) => GetAllResponse.fromJson(json))
    .toList();
